version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: ldb
    ports:
      - "5432:3306"
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_ROOT_PASSWORD=library1818
    volumes:
      - mysql_data:/var/lib/mysql
  libraryapi:
    container_name: lapi
    build: 
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    volumes:
      - .:/app
    links:
      - "mysqldb:db"
volumes:
  mysql_data: